version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "**/__fixtures__/**"
      - "**/test/fixtures/**"
  - package-ecosystem: "npm"
    directory: "/packages/"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "**/__fixtures__/**"
      - "**/test/fixtures/**"
